version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      # Install dependencies including pylint for static code analysis
      - pip install -r requirements.txt pylint

  pre_build:
    commands:
      # Display the Python version for debugging purposes
      - python --version
      # Run pylint on the root directory and subdirectories
      - pylint $CODEBUILD_SRC_DIR/demoproj/*.py
      - pylint $CODEBUILD_SRC_DIR/demoproj/demoproj/*.py

artifacts:
  files:
    - '**/*'